name: ci-cd
on: [push]

jobs:
  build-and-run:
    name: build-and-run
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build-docker-image
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: claudiobizzotto/go-http-echo-server
          tags: latest
      - name: run-docker-container
        if: success()
        # uses: docker://claudiobizzotto/go-http-echo-server:latest
        run: |
          docker run -d -p 8080:8080 go-http-echo-server
          curl -i http://localhost:8080/
