name: ci-cd
on: [push]

jobs:
  build-and-run:
    name: build-and-run
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build-docker-image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: claudiobizzotto/go-http-echo-server
          tags: latest
