name: ci-cd
on: [push]

jobs:
  build-and-run:
    name: build-and-run
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build-docker-image
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: claudiobizzotto/go-http-echo-server
          tags: latest
      - name: run-docker-container
        if: success()
        run: |
          docker run -d -p 8080:8080 claudiobizzotto/go-http-echo-server
          docker ps
          wget -S http://127.0.0.1:8080
